const path = require('node:path');
const os = require('node:os');

const DEFAULT_DATA_ROOT = process.env.ORCH_DATA_DIR || path.join(os.homedir(), '.codex-orchestrator-data');
const DEFAULT_ORCH_HOME = path.join(DEFAULT_DATA_ROOT, '.codex-orchestrator');
const DEFAULT_CODEX_HOME = path.join(DEFAULT_DATA_ROOT, '.codex');
const DEFAULT_GIT_CONFIG_GLOBAL = path.join(DEFAULT_DATA_ROOT, 'git', '.gitconfig');
const DEFAULT_GIT_CONFIG_CONTAINER_PATH = '/orchestrator-git/.gitconfig';
const DEFAULT_GIT_CONFIG_CONTAINER_DIR = '/orchestrator-git';
const DEFAULT_INNER_CODEX_HOME = '/root/.codex';
const DEFAULT_INNER_ARTIFACTS_DIR = '/root/.artifacts';
const DEFAULT_IMAGE_NAME = 'ghcr.io/andreimarhatau/codex-docker:latest';
const DEFAULT_TASK_DEVELOPER_INSTRUCTIONS_FILE = path.join(
  __dirname,
  '..',
  '..',
  '..',
  'DEVELOPER_TASK_INSTRUCTIONS.md'
);
const DEFAULT_CONTEXT_REPOS_TEMPLATE_FILE = path.join(
  __dirname,
  '..',
  '..',
  '..',
  'ORCHESTRATOR_CONTEXT_REPOS_TEMPLATE.md'
);
const DEFAULT_ATTACHMENTS_TEMPLATE_FILE = path.join(
  __dirname,
  '..',
  '..',
  '..',
  'ORCHESTRATOR_ATTACHMENTS_TEMPLATE.md'
);
const COMMIT_SHA_REGEX = /^[0-9a-f]{7,40}$/i;
const DEFAULT_GIT_CREDENTIAL_HELPER = '!/usr/bin/gh auth git-credential';
const DEFAULT_ACCOUNT_ROTATION_LIMIT = 'auto';
const MAX_DIFF_LINES = 400;
const DEFAULT_TASK_DOCKER_SIDECAR_IMAGE = 'docker:27-dind';
const DEFAULT_TASK_DOCKER_SIDECAR_NAME_PREFIX = 'codex-task-docker';
const DEFAULT_TASK_DOCKER_READY_TIMEOUT_MS = 600_000;
const DEFAULT_TASK_DOCKER_READY_INTERVAL_MS = 500;
const DEFAULT_TASK_DOCKER_COMMAND_TIMEOUT_MS = 600_000;

module.exports = {
  DEFAULT_DATA_ROOT,
  DEFAULT_ORCH_HOME,
  DEFAULT_CODEX_HOME,
  DEFAULT_GIT_CONFIG_GLOBAL,
  DEFAULT_GIT_CONFIG_CONTAINER_PATH,
  DEFAULT_GIT_CONFIG_CONTAINER_DIR,
  DEFAULT_INNER_CODEX_HOME,
  DEFAULT_INNER_ARTIFACTS_DIR,
  DEFAULT_IMAGE_NAME,
  DEFAULT_TASK_DEVELOPER_INSTRUCTIONS_FILE,
  DEFAULT_CONTEXT_REPOS_TEMPLATE_FILE,
  DEFAULT_ATTACHMENTS_TEMPLATE_FILE,
  COMMIT_SHA_REGEX,
  DEFAULT_GIT_CREDENTIAL_HELPER,
  DEFAULT_ACCOUNT_ROTATION_LIMIT,
  MAX_DIFF_LINES,
  DEFAULT_TASK_DOCKER_SIDECAR_IMAGE,
  DEFAULT_TASK_DOCKER_SIDECAR_NAME_PREFIX,
  DEFAULT_TASK_DOCKER_READY_TIMEOUT_MS,
  DEFAULT_TASK_DOCKER_READY_INTERVAL_MS,
  DEFAULT_TASK_DOCKER_COMMAND_TIMEOUT_MS
};
